_core:
  default_config_hash: 1SNdA25INsV5YjlgAJtfC-6AM8VcWe_00xneMLb2yFg
langcode: en
message: 'This site is coming soon. In the meantime, please visit the archive at <a href="https://archive.howeverhow2archive.org/">archive.howeverhow2archive.org</a>.'
