_core:
  default_config_hash: 1SNdA25INsV5YjlgAJtfC-6AM8VcWe_00xneMLb2yFg
langcode: en
message: "<i>This site is coming soon.</i><br>\r\nIn the meantime, please visit the legacy archive at<br>\r\n<a href=\"https://archive.howeverhow2archive.org/\">archive.howeverhow2archive.org</a>"
