_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7d5f67f6-7cc1-455a-815b-06e9c9cc77c5
name: 'HOW(ever) / How2 Archives'
mail: sean@proofstudio.co
slogan: ''
page:
  403: ''
  404: ''
  front: /node/69
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
